version: 2

project_name: gopherlint

builds:
  - binary: gopherlint
    main: ./cmd/gopherlint/
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
      - freebsd
      - netbsd
      - illumos
    goarch:
      - amd64
      - arm64
      - arm
      - 386
      - ppc64le
      - s390x
      - mips64
      - mips64le
      - riscv64
      - loong64
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
    ignore:
      - goos: darwin
        goarch: 386
      # Deprecated in go1.25, Removed in go1.26
      # https://go.dev/doc/go1.25#windows
      - goos: windows
        goarch: arm

archives:
  - formats: [ 'tar.gz' ]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^docs\([^:]+\):'
      - '(?i)^docs\[[^:]+\]:'
      - '^tests?:'
      - '(?i)^dev:'
      - '(?i)^chore:'
      - '^build\(deps\): bump .* in /docs \(#\d+\)'
      - '^build\(deps\): bump .* in /\.github/peril \(#\d+\)'
      - '^build\(deps\): bump .* in /scripts/gen_github_action_config \(#\d+\)'
      - Merge pull request
      - Merge branch

release:
  skip_upload: false
  github:
    owner: flimzy
    name: gopherlint

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'


nfpms:
  - description: Fast linters Runner for Go
    homepage: https://github.com/flimzy/gopherlint
    id: gopherlint-nfpms
    package_name: gopherlint
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    maintainer: "gopherlint Maintainers"
    license: GPLv3
    vendor: flimzy
    section: golang
    formats:
      - deb
      - rpm
    umask: 0o022
    overrides:
      deb:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/gopherlint/copyright
          - src: README.md
            dst: /usr/share/doc/gopherlint/README.md
        recommends:
          - golang-go
      rpm:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/gopherlint/LICENSE
            type: license
          - src: README.md
            dst: /usr/share/doc/gopherlint/README.md
            type: readme
        recommends:
          - /usr/bin/go
    rpm:
      group: Development/Tools

