- id: gopherlint
  name: gopherlint
  description: Fast linters runner for Go. Note that only modified files are linted, so linters like 'unused' that need to scan all files won't work as expected.
  entry: gopherlint run --new-from-rev HEAD --fix
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
- id: gopherlint-full
  name: gopherlint-full
  description: Fast linters runner for Go. Runs on all files in the module. Use this hook if you use pre-commit in CI.
  entry: gopherlint run --fix
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
- id: gopherlint-fmt
  name: gopherlint-fmt
  description: Fast linters runner for Go. Formats all files in the repo.
  entry: gopherlint fmt
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
- id: gopherlint-config-verify
  name: gopherlint-config-verify
  description: Verifies the configuration file
  entry: gopherlint config verify
  files: '\.golangci\.(?:yml|yaml|toml|json)'
  language: golang
  pass_filenames: false
