name: 💡 Feature request
description: "Note: gopherlint does not accept feature requests."
body:
  - type: markdown
    attributes:
      value: |
        **gopherlint is a bugfix-only fork.** New features and linter additions are out of scope.

        If you'd like a new feature or linter, please open a request with the upstream project:
        👉 [golangci-lint issues](https://github.com/golangci/golangci-lint/issues/new/choose)
